CREATE TABLE `nodes` ( `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT , `name` TEXT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `nodes` ADD `status` BOOLEAN NOT NULL AFTER `name`;
ALTER TABLE `nodes` ADD geom POINT;